import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ title }) {
  // const title = dashboard;
  return (
    <>
      <Head>
        <title>{ title ? title : "Health Insurance System" }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      </main>
    </>
  )
}
